name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yarn install
      run: yarn install
    - name: yarn test
     run: yarn test
